site_name: DiscordBotExt
repo_url: https://github.com/lonnstyle/DiscordBotExt
repo_name: DiscordBotExt
site_author: lonnstyle
copyright: © 2021 lonnstyle
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust