INHERIT: base.yml
site_dir: ../site
use_directory_urls: False

nav:
    - 歡迎: index.md
    - 快速安裝: quickInstall.md
    - 指令擴展: ext.md
    - 現成的指令擴展:
        - admin.py: ext/admin.md
        - baro.py: ext/baro.md
        - common.py: ext/common.md
        - event.py: ext/event.md
        - rivenPrice.py: ext/rivenPrice.md
        - wfm.py:   ext/wfm.md
        - wiki.py:  ext/wiki.md
        - worldState.py:    ext/worldState.md
    - 關於:
        - 贊助: donate.md
